apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-tracker
  labels:
    app: student-tracker
spec:
  # Specify the number of pod replicas to run
  replicas: 2
  selector:
    matchLabels:
      app: student-tracker
  template:
    metadata:
      labels:
        app: student-tracker
    spec:
      containers:
      - name: student-tracker
        image: divyansh4383/student-tracker:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
