apiVersion: v1
kind: Service
metadata:
  name: student-tracker-service
  labels:
    app: student-tracker
spec:
  type: NodePort
  selector:
    app: student-tracker
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30001
